<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <StaticWebAssetBasePath>App_Plugins/$(AssemblyName)</StaticWebAssetBasePath>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <VersionPrefix>17.0.5</VersionPrefix>
    <VersionSuffix Condition="'$(Configuration)'=='Debug'">build$([System.DateTime]::UtcNow.ToString(`yyyyMMddHHmm`))</VersionSuffix>
    <Authors>Anders Bjerner</Authors>
    <Company>Limbo</Company>
    <Title>Skybrud Redirects</Title>
    <Description>Redirects manager for Umbraco.</Description>
    <Copyright>Copyright © $([System.DateTime]::UtcNow.ToString(`yyyy`))</Copyright>
  </PropertyGroup>

  <!-- Information for the NuGet package -->
  <PropertyGroup>
    <PackageId>Skybrud.Umbraco.Redirects</PackageId>
    <PackageTags>Umbraco, Redirects, Redirect, 301, 307, Content, Url, Skybrud, Limbo, Umbraco-Marketplace</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://packages.skybrud.dk/skybrud.umbraco.redirects/</PackageProjectUrl>
    <PackageIcon>Limbo.png</PackageIcon>
    <PackageReadmeFile>NUGET.md</PackageReadmeFile>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/skybrud/Skybrud.Umbraco.Redirects</RepositoryUrl>
  </PropertyGroup>

  <!-- Include additional metadata in the assembly -->
  <ItemGroup>
    <AssemblyMetadata Include="PackageProjectUrl" Value="https://packages.limbo.works/skybrud.umbraco.redirects/" />
    <AssemblyMetadata Include="DocumentationUrl" Value="https://packages.limbo.works/skybrud.umbraco.redirects/docs/v17/" />
    <AssemblyMetadata Include="NuGetUrl" Value="https://www.nuget.org/packages/Skybrud.Umbraco.Redirects" />
    <AssemblyMetadata Include="UmbracoMarketplaceUrl" Value="https://marketplace.umbraco.com/package/skybrud.umbraco.redirects" />
  </ItemGroup>

  <!-- Ignore vulnerabilities from transient dependencies -->
  <ItemGroup>

    <!-- Package 'MessagePack' 3.1.4 has a known high severity vulnerability -->
    <NuGetAuditSuppress Include="https://github.com/advisories/GHSA-382j-8mxh-c7x2" />
    <NuGetAuditSuppress Include="https://github.com/advisories/GHSA-hv8m-jj95-wg3x" />
    <NuGetAuditSuppress Include="https://github.com/advisories/GHSA-vh6j-jc39-fggf" />

    <!-- Package 'MessagePack' 3.1.4 has a known medium severity vulnerability -->
    <NuGetAuditSuppress Include="https://github.com/advisories/GHSA-qhmf-xw27-6rqr" />
    <NuGetAuditSuppress Include="https://github.com/advisories/GHSA-q2h6-ghwm-5qm8" />
    <NuGetAuditSuppress Include="https://github.com/advisories/GHSA-v72x-2h86-7f8m" />
    <NuGetAuditSuppress Include="https://github.com/advisories/GHSA-2f33-pr97-265q" />
    <NuGetAuditSuppress Include="https://github.com/advisories/GHSA-2x83-8g95-xh59" />
    <NuGetAuditSuppress Include="https://github.com/advisories/GHSA-cj9g-3mj2-g8vv" />
    <NuGetAuditSuppress Include="https://github.com/advisories/GHSA-cxmj-83gh-fp49" />
    <NuGetAuditSuppress Include="https://github.com/advisories/GHSA-w567-gjr2-hm5j" />
    <NuGetAuditSuppress Include="https://github.com/advisories/GHSA-wfr3-xj75-pfwh" />

    <!-- Package 'MimeKit' 4.14.0 has a known moderate severity vulnerability -->
    <NuGetAuditSuppress Include="https://github.com/advisories/GHSA-g7hc-96xr-gvvx" />

    <!-- Package 'MailKit' 4.14.0 has a known moderate severity vulnerability -->
    <NuGetAuditSuppress Include="https://github.com/advisories/GHSA-9j88-vvj5-vhgr" />

    <!-- Package 'System.Security.Cryptography.Xml' 8.0.0 has a known high severity vulnerability -->
    <NuGetAuditSuppress Include="https://github.com/advisories/GHSA-37gx-xxp4-5rgx" />
    <NuGetAuditSuppress Include="https://github.com/advisories/GHSA-w3x6-4m5h-cxqf" />

  </ItemGroup>

  <!-- Include NuGet dependencies -->
  <ItemGroup>
    <PackageReference Include="Skybrud.Essentials" Version="1.1.67" />
    <PackageReference Include="Umbraco.Cms.Core" Version="[17.0.0,17.999)" />
    <PackageReference Include="Umbraco.Cms.Web.Website" Version="[17.0.0,17.999)" />
  </ItemGroup>

  <!-- Include package icon and README for the NuGet package -->
  <ItemGroup>
    <Content Include="../build/Limbo.png" Pack="true" PackagePath="\" />
    <None Include="..\..\NUGET.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <!-- Generate XML documentation -->
  <PropertyGroup>
    <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
  </PropertyGroup>

</Project>